#########################################
# The "development" compose file builds 
# the images locally
#########################################

#version: "3"

services:
  api:
    image: $DOCKERHUB_UNAME/recipe_backend:$NEW_VERSION
    restart: always
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - DB_NAME=$POSTGRES_DB
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
    depends_on:
      #- db
      db:
        condition: service_healthy
  nginx:
    image: $DOCKERHUB_UNAME/recipe_frontend:$NEW_VERSION
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
  db:
    image: postgres:15
    restart: always  # Restart upom failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
