# Generated by Django 5.1.5 on 2025-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0003_shoppinglistitem_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, null=True),
        ),
    ]
