# Generated by Django 5.1.5 on 2025-03-26 01:23

import django.db.models.deletion
import saved_recipes_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMeal', models.CharField(max_length=5, unique=True, validators=[saved_recipes_app.validators.validate_id_meal])),
                ('recipe_title', models.CharField(max_length=100, unique=True)),
                ('meal_pic_img', models.CharField(max_length=400, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idMeal', 'recipe_title', 'meal_pic_img'), name='unique_recipe')],
            },
        ),
    ]
