# Generated by Django 5.1.5 on 2025-03-21 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_recipes_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='saved_recipes',
            constraint=models.UniqueConstraint(fields=('idMeal', 'recipe_title'), name='unique_recipe'),
        ),
    ]
